"""initial_schema

Revision ID: 165758b92e47
Revises: 
Create Date: 2026-10-07 10:34:21.037785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165758b92e47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_printers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_serial', sa.String(length=100), nullable=False),
    sa.Column('type_action', sa.String(length=30), nullable=False),
    sa.Column('origin_action', sa.Text(), nullable=False),
    sa.Column('named_event', sa.String(length=30), nullable=True),
    sa.Column('field_name', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('user_action', sa.String(length=100), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_date', 'log_printers', ['action_date'], unique=False)
    op.create_index('ix_log_serial', 'log_printers', ['num_serial'], unique=False)
    op.create_table('positions',
    sa.Column('ip', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('branches',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_branch', sa.String(length=10), server_default=sa.text("'filial'"), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_networks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ip_version', sa.String(length=10), server_default=sa.text("'ipv4'"), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('collector_type', sa.String(length=30), server_default=sa.text("'snmp'"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('ip_start', sa.BINARY(length=16), nullable=False),
    sa.Column('ip_end', sa.BINARY(length=16), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_networks_ip_end'), 'branch_networks', ['ip_end'], unique=False)
    op.create_index(op.f('ix_branch_networks_ip_start'), 'branch_networks', ['ip_start'], unique=False)
    op.create_table('printers',
    sa.Column('num_serial', sa.String(length=100), nullable=False),
    sa.Column('branch_native_id', sa.Integer(), nullable=False),
    sa.Column('branch_current_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('printer_type', sa.String(length=30), server_default=sa.text("'laser'"), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=18), nullable=True),
    sa.Column('connection_type', sa.String(length=30), server_default=sa.text("'ip'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'online'"), nullable=False),
    sa.Column('collector_type', sa.String(length=30), server_default=sa.text("'snmp'"), nullable=False),
    sa.Column('counter', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('printer_function', sa.String(length=30), server_default=sa.text("'operacional'"), nullable=False),
    sa.Column('last_modify', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('info_additional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_current_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['branch_native_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['branch_networks.id'], ),
    sa.PrimaryKeyConstraint('num_serial')
    )
    op.create_table('daily_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_serial', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=18), nullable=True),
    sa.Column('status_counter', sa.String(length=30), nullable=False),
    sa.Column('errors', sa.String(length=200), nullable=True),
    sa.Column('ini_counter', sa.Integer(), nullable=False),
    sa.Column('ini_date', sa.Date(), nullable=False),
    sa.Column('end_counter', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['num_serial'], ['printers.num_serial'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_serial', 'date', 'branch_id', name='uq_daily_serial_branch_date')
    )
    op.create_index('ix_branch_date', 'daily_counters', ['branch_id', 'date'], unique=False)
    op.create_index('ix_serial_date', 'daily_counters', ['num_serial', 'date'], unique=False)
    op.create_table('data_error_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_serial', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=18), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('named_error', sa.String(length=100), nullable=True),
    sa.Column('date_error', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['num_serial'], ['printers.num_serial'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_serial', 'branch_id', 'date_error', name='uq_error_serial_branch_date')
    )
    op.create_index('ix_error_serial_date', 'data_error_counters', ['num_serial', 'date_error'], unique=False)
    op.create_table('data_raw_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_serial', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=18), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('date_reading', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['num_serial'], ['printers.num_serial'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_serial_date', 'data_raw_counters', ['num_serial', 'date_reading'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_serial_date', table_name='data_raw_counters')
    op.drop_table('data_raw_counters')
    op.drop_index('ix_error_serial_date', table_name='data_error_counters')
    op.drop_table('data_error_counters')
    op.drop_index('ix_serial_date', table_name='daily_counters')
    op.drop_index('ix_branch_date', table_name='daily_counters')
    op.drop_table('daily_counters')
    op.drop_table('printers')
    op.drop_index(op.f('ix_branch_networks_ip_start'), table_name='branch_networks')
    op.drop_index(op.f('ix_branch_networks_ip_end'), table_name='branch_networks')
    op.drop_table('branch_networks')
    op.drop_table('branches')
    op.drop_table('positions')
    op.drop_index('ix_log_serial', table_name='log_printers')
    op.drop_index('ix_log_date', table_name='log_printers')
    op.drop_table('log_printers')
    op.drop_table('companies')
    # ### end Alembic commands ###
